name: CI

on:
  - pull_request
  - push

jobs:
  tests:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        php: ['5.6', '7.0', '7.1', '7.2', '7.3', '7.4', '8.0', '8.1', '8.2']
    name: PHP ${{ matrix.php }}
    steps:
      -   uses: actions/checkout@v3
      # required for "git tag" presence for MonorepoBuilder split and ChangelogLinker git tags resolver; default is 1
      -   run: git fetch --depth=100000 origin
      # see https://github.com/shivammathur/setup-php
      -   uses: shivammathur/setup-php@v2
          with:
            php-version: ${{ matrix.php }}
            extensions: dom, json
            coverage: xdebug
      -   run: composer install --no-progress
      -   run: composer test
